### PR TITLE
Vehicle Stats save loop for Garage module

### PR DESCRIPTION
**Pull request by zicongqiu**

### CODE REVIEW

**Comment by Haizanjs** [comment]
If I were you I would work on making it configurable for either a hit save basis or individual hitpoint damage basis. e.g. save array of all the individual damage values to each part.

https://community.bistudio.com/wiki/getHitPointDamage

^ Reference if you're wondering

**Comment by kerkkoh** [comment]
We already save all hitpoints as an array. See https://github.com/RPFramework/RPFramework/blob/development/RPFramework.Altis/Functions/core/Vehicle/fn_vehicleHitGet.sqf but I also noticed that we are calling it from the server even though it's on the client's side 😂 fuck.

**Comment by zicongqiu** [comment]
i understand there is vehicleHitGet function which saves hit data into an array, but this is a saving loop utilizing that function so vehicles' hitpoint data gets saved to the DB.

**Comment by Haizanjs** [comment]
I personally think it’s unneeded to loop hit damage. It should only be saved to the database upon disconnecting from the server, storing the vehicle.

**Comment by kerkkoh** [comment]
@Haizanjs Well you now have a config toggle for that so you can disable it if you wish to do so.

**Comment by Haizanjs** [comment]
Just seems extremely unneeded to save it this way.

**Comment by kerkkoh** [comment]
Feel free to disable it on your end. I bet someone would love to have this feature in so there it is.

**Comment by Haizanjs** [comment]
@kerkkoh I'll let people be people then ;P

**Pull request merged**
