### PR TITLE
(!) instead of (not) fn_insideHouseConditions.sqf

### PR DESCRIPTION
**Pull request by Haizanjs**

### CODE REVIEW

**Comment by kerkkoh** [comment]
I think cuffTarget is already spawned so you can remove the spawn from it afaik.

**Comment by Haizanjs** [comment]
@kerkkoh it's remoteExec on the target clientOwner so having the [] spawn with be needed?

**Comment by Haizanjs** [comment]
nvm yeah, the [] spawn won't be needed. will remove now

**Comment by Haizanjs** [comment]
@kerkkoh Added some more juice for you to review 💯

**Comment by kerkkoh** [comment]
Good catches. Have you tested that all of the changed scripts work in a live environment like you would want them to?

**Comment by Haizanjs** [comment]
I'll test in live environment  shortly and post results.

**Comment by Haizanjs** [comment]
No errors for RPT nor no script errors for modified code.

[Arma3_x64_2018-02-26_16-45-08.txt << Client RPT](https://github.com/RPFramework/RPFramework/files/1759592/Arma3_x64_2018-02-26_16-45-08.txt)

[arma3server_x64_2018-02-26_16-44-52.txt << Server RPT](https://github.com/RPFramework/RPFramework/files/1759596/arma3server_x64_2018-02-26_16-44-52.txt)

^^ There is an error though with RPT_Mining as the Addon probably isn't found, this hasn't been an issue as of my commits. This was a prior occurrence.

**Comment by kerkkoh** [comment]
Yeah, the mining log spam has been a problem since forever.

**Comment by Haizanjs** [comment]
Now for the mining log spam, seeming it's been an issue. Is it because the mining module isn't working or ?

**Comment by kerkkoh** [comment]
It's working fine. It's just a little cosmetic thing in the log.

**Pull request merged**
