### PR TITLE
New Icons and Delivery Module

### PR DESCRIPTION
**Pull request by jschmidt92**
I created new Icons for the survival GUI and started working on a delivery module for the framework. I'm not sure if the delivery module I've started working on meets your needs or expectations. I've also started working on implementing more features to the survival GUI i.e hygiene, bladder, and energy.

### CODE REVIEW

**Comment by kerkkoh** [comment]
I'll review the changes to the UI and see what I'm going to merge. I was working on some delivery module already, but your code will help a lot with that.

Not sure if hygiene, bladder, and energy will be included in the core, but if they can be made into modules, that would be perfect. If you want to already do these changes to the pull request, that would speed things up a bit.

**Comment by jschmidt92** [comment]
Sounds good, the only issue I'm having is deleting the unit that spawns in, in which you deliver the package to. And I haven't tested it with other people yet, but it does work on a dedicated server.

**Comment by kerkkoh** [comment]
I'll download your repository as it is and update the icons when I update the HUD a little bit. I'll include it all in the next release. Hope you won't mind if I mention you in the contributors?

**Comment by jschmidt92** [comment]
K, and I don't mind if you mention me.  And if you'd like to you can add me your Dev Team here on GitHub and on Trello.

**Comment by kerkkoh** [comment]
I'm planning to keep the Trello board just to my personal development of modules and the core.

Switched RPFramework to its own organization and invited you to it.

With this, I'll close the pull request and implement the changes I can to the new update.

**Pull request closed without merging**
