### PR TITLE
Security && Opti

### PR DESCRIPTION
**Pull request by NiiRoZz**
CursorTarget ---> CursorObject
&&
BIS_fnc_MP --- > RemoteExecCall
&&
While ----> for do
&&
For commands restriction inside cfgremoteexec i don't know what commands used
So if you can put just command you use

### CODE REVIEW

**Comment by kerkkoh** [comment]
Some conflicts due to my extdb3 update but has this been tested?

**Comment by NiiRoZz** [comment]
Don't have time to test because i don't have test server with rpframework sorry

**Comment by kerkkoh** [comment]
Ok. I can try to resolve the issues and test it if you want

**Comment by NiiRoZz** [comment]
Yes if you can it's nice

**Comment by kerkkoh** [comment]
Running tests tomorrow and then committing it.

**Comment by kerkkoh** [comment]
Now merging and updating. Version won't be backwards compatible so version 3.0.0.

**Pull request closed without merging**
